name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libpcap
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libpcap
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - name: Run unit tests.
        run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libpcap
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - name: Build
        run: make build
